version: '3.5'

services:
    frontend:
        build: ./front
        ports:
            - 5000:5000


    backend:
        build: ./back
        ports:
            - 8000:8000
        environment: 
            - REDIS=redis
            - DB_USERNAME=testi
            - DB_PASSWORD=testinen
            - DB_NAME=testiDB
            - DB_HOST=db


    proxy:
        image: jwilder/nginx-proxy
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    
    redis:
        image: redis

    
    db:
        image: postgres
        environment: 
            - POSTGRES_USER=testi
            - POSTGRES_PASSWORD=testinen
            - POSTGRES_DB=testiDB