version: '3.5'

services:
    ml-kurkkumopo-frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
        

    ml-kurkkumopo-backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes:
            - model:/src/model


    ml-kurkkumopo-training:
        build: ./ml-kurkkumopo-training
        volumes:
            - imgs:/src/imgs
            - model:/src/model
            - data:/src/data

volumes:
    imgs:
    model:
    data: